# Generated by Django 2.2.2 on 2019-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
