# Generated by Django 2.2.2 on 2019-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20190821_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
