# Generated by Django 2.2.2 on 2019-08-19 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0004_auto_20190819_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('optionA', models.CharField(blank=True, max_length=200, null=True)),
                ('optionB', models.CharField(blank=True, max_length=200, null=True)),
                ('optionC', models.CharField(blank=True, max_length=200, null=True)),
                ('optionD', models.CharField(blank=True, max_length=200, null=True)),
                ('correct', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=2)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
        ),
    ]
