# Generated by Django 2.2.2 on 2019-08-20 06:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0004_auto_20190819_1551'),
        ('quiz', '0002_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Module_Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.CharField(blank=True, max_length=3, null=True)),
                ('correct', models.CharField(blank=True, max_length=2, null=True)),
                ('wrong', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
                ('student', models.ForeignKey(limit_choices_to={'role': '3'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
