# Generated by Django 2.2.2 on 2019-08-07 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('0', 'Basic Training'), ('1', 'On Job Training')], max_length=2)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default=0, max_length=2)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Center')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Course')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': '4'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
