# Generated by Django 2.2.2 on 2019-08-09 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_end',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='class_start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='days',
            field=models.CharField(choices=[('0', 'Weekdays'), ('1', 'Weekends')], default='0', max_length=2),
        ),
    ]
