# Generated by Django 2.2.2 on 2019-08-14 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0003_auto_20190809_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(max_length=2)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=2)),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('lead_sourse', models.CharField(max_length=100)),
                ('lead_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default=0, max_length=2)),
                ('course_fee', models.CharField(blank=True, default=0, max_length=7, null=True)),
                ('lms_id', models.CharField(default=0, max_length=2)),
                ('lms_username', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.Batch')),
                ('counsellor', models.ForeignKey(limit_choices_to={'role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Course')),
            ],
        ),
    ]
