# Generated by Django 2.2.2 on 2019-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='tms_id',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
